X_SCALE = 48
Y_SCALE = 48

AGENT_OPEN_SPACE = 0
AGENT_WALL = 1
AGENT_DOOR_OPEN = 2
AGENT_DOOR_CLOSED = 3
AGENT_LADDER = 4
AGENT_BOLT_LOCKED = 5
AGENT_BOLT_UNLOCKED = 6
AGENT_GOLD = 7
AGENT_HANDLE_UP = 8
AGENT_HANDLE_DOWN = 9
AGENT_KEY = 10
# AGENT_NORMALISE_CONSTANT = 10
AGENT_NORMALISE_CONSTANT = 1


OPEN_SPACE = ' '
WALL = '/'
DOOR = 'D'
HANDLE = 'H'
LADDER = 'L'
BOLT = 'B'
GOLD = 'G'

ACTION_NOP = 0
ACTION_UP = 1
ACTION_DOWN = 2
ACTION_LEFT = 3
ACTION_RIGHT = 4
ACTION_JUMP = 5
ACTION_INTERACT = 6

BACKGROUND_SPRITE = 0
WALL_SPRITE = 1
LADDER_SPRITE = 2
DOOR_CLOSED_SPRITE = 3
DOOR_OPEN_SPRITE = 4
KEY_SPRITE = 5
COIN_SPRITE = 6
BOLT_OPEN_SPRITE = 7
BOLT_CLOSED_SPRITE = 8
HERO_SPRITE = 9
HANDLE_BASE_SPRITE = 10
HANDLE_SHAFT_SPRITE = 11
FLOOR_SPRITE = 12